<?php
$file = '/var/www/html/university_lesson.php';
$content = file_get_contents($file);
$func = "\nfunction make_embed_url(string \$url): string {\n    if (preg_match('/youtube\.com\/watch\?.*v=([a-zA-Z0-9_-]+)/', \$url, \$m)) return 'https://www.youtube.com/embed/' . \$m[1];\n    if (preg_match('/youtu\.be\/([a-zA-Z0-9_-]+)/', \$url, \$m)) return 'https://www.youtube.com/embed/' . \$m[1];\n    if (preg_match('/vimeo\.com\/(\d+)/', \$url, \$m)) return 'https://player.vimeo.com/video/' . \$m[1];\n    return \$url;\n}\n\$embedUrl = !empty(\$lesson['embed_url']) ? make_embed_url(\$lesson['embed_url']) : '';\n";
$content = str_replace("\$lessonNum = \$lessonIndex !== false ? \$lessonIndex + 1 : 1;\n?>", "\$lessonNum = \$lessonIndex !== false ? \$lessonIndex + 1 : 1;" . $func . "\n?>", $content, $c1);
$oldV = "      <?php if (\$lesson['file_key']): ?>\n      <div class=\"video-wrap\">\n        <video id=\"lesson-video\" controls preload=\"metadata\" onended=\"onVideoEnd()\">\n          <source src=\"api/uni_download.php?id=<?= \$lessonId ?>\" type=\"video/mp4\">\n          Your browser does not support video playback.\n        </video>\n      </div>\n      <?php else: ?>\n      <div class=\"doc-wrap\" style=\"background:#fff3cd;border-color:#ffc107\">\n        <div class=\"doc-icon\">&#9888;</div>\n        <div class=\"doc-title\">Video not uploaded yet</div>\n      </div>\n      <?php endif; ?>";
$newV = "      <?php if (\$embedUrl): ?>\n      <div class=\"video-wrap\" style=\"padding-top:56.25%;position:relative;background:#000;border-radius:10px;overflow:hidden;margin-bottom:20px\">\n        <iframe src=\"<?= htmlspecialchars(\$embedUrl) ?>\" style=\"position:absolute;top:0;left:0;width:100%;height:100%;border:0\" allowfullscreen allow=\"autoplay; fullscreen; picture-in-picture\" onload=\"scheduleEmbedComplete()\"></iframe>\n      </div>\n      <?php elseif (\$lesson['file_key']): ?>\n      <div class=\"video-wrap\">\n        <video id=\"lesson-video\" controls preload=\"metadata\" onended=\"onVideoEnd()\">\n          <source src=\"api/uni_download.php?id=<?= \$lessonId ?>\" type=\"video/mp4\">\n          Your browser does not support video playback.\n        </video>\n      </div>\n      <?php else: ?>\n      <div class=\"doc-wrap\" style=\"background:#fff3cd;border-color:#ffc107\">\n        <div class=\"doc-icon\">&#9888;</div>\n        <div class=\"doc-title\">Video not uploaded yet</div>\n      </div>\n      <?php endif; ?>";
$content = str_replace($oldV, $newV, $content, $c2);
file_put_contents($file, $content);
echo "func=$c1 video=$c2\n";
